
import React from "react";
import { User, Check } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { AccountTypeTooltip } from "./AccountTypeTooltip";

type AccountType = "Customer" | "Monto";

interface AccountTypeSectionProps {
  selectedAccountType: AccountType;
  onAccountTypeSelect: (type: AccountType) => void;
  connectionInfo: {
    receivable: string;
    payable: string;
  };
  montoSetupConfirmed: boolean;
  onMontoSetupConfirmedChange: (checked: boolean | "indeterminate") => void;
}

export function AccountTypeSection({
  selectedAccountType,
  onAccountTypeSelect,
  connectionInfo,
  montoSetupConfirmed,
  onMontoSetupConfirmedChange
}: AccountTypeSectionProps) {
  const renderAccountTypeCard = (type: AccountType, title: string, description: string) => {
    const isSelected = selectedAccountType === type;
    const isMonto = type === "Monto";
    
    return (
      <AccountTypeTooltip type={type} key={type}>
        <div
          className={`p-4 rounded-xl border cursor-pointer transition-all relative ${
            isSelected
              ? isMonto 
                ? "bg-[#EEEAFF] border-[#7B59FF]"
                : "bg-gray-100 border-gray-300"
              : "bg-white border-gray-200" + (isMonto ? " hover:border-gray-300" : "")
          }`}
          onClick={() => onAccountTypeSelect(type)}
        >
          {isMonto && (
            <div className="absolute top-2 right-2">
              <span className="bg-green-100 text-green-800 text-xs font-medium px-2 py-1 rounded-full">
                Recommended
              </span>
            </div>
          )}
          <div className="flex items-center gap-3 mb-2">
            <User className="h-5 w-5 text-gray-600" />
            <span className="font-medium text-gray-900">{title}</span>
          </div>
          <p className="text-sm text-gray-600">{description}</p>
        </div>
      </AccountTypeTooltip>
    );
  };

  const autoGeneratedEmail = `${connectionInfo.receivable.toLowerCase().replace(/\s+/g, '')}@montopay.com`;

  const renderMontoSetupInstructions = () => {
    if (selectedAccountType !== "Monto") return null;

    return (
      <div className="w-full p-4 bg-[#EEEAFF] border border-[#7B59FF] rounded-xl">
        <h4 className="font-medium text-gray-900 mb-4">Setup Instructions</h4>
        
        <div className="space-y-4">
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              1
            </div>
            <p className="text-sm text-gray-700">Log into your portal and navigate to user management</p>
          </div>
          
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              2
            </div>
            <div className="flex-1">
              <p className="text-sm text-gray-700 mb-2">Create a user using the auto-generated Monto email:</p>
              <div className="flex items-center gap-2">
                <div className="flex-1 p-2 bg-white border rounded text-sm text-blue-600 font-mono">
                  {autoGeneratedEmail}
                </div>
              </div>
            </div>
          </div>
          
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              3
            </div>
            <div className="flex-1">
              <p className="text-sm text-gray-700 mb-2">Permission requirements:</p>
              <div className="space-y-1 ml-2">
                <div className="flex items-center gap-2 text-sm text-gray-700">
                  <Check className="h-4 w-4 text-green-600" />
                  <span>Full access to invoice submission</span>
                </div>
                <div className="flex items-center gap-2 text-sm text-gray-700">
                  <Check className="h-4 w-4 text-green-600" />
                  <span>Full access to portal management</span>
                </div>
              </div>
            </div>
          </div>
          
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              4
            </div>
            <p className="text-sm text-gray-700">Set a strong password and configure 2FA if required</p>
          </div>
          
          <div className="pt-4 border-t border-[#7B59FF]/20">
            <div className="flex items-center space-x-2">
              <Checkbox 
                id="monto-setup" 
                checked={montoSetupConfirmed}
                onCheckedChange={onMontoSetupConfirmedChange}
              />
              <label htmlFor="monto-setup" className="text-sm text-gray-700 cursor-pointer">
                I've created this dedicated user in the portal
              </label>
            </div>
            <p className="text-xs text-blue-600 mt-1 ml-6">
              Check this box once you've completed the setup steps above in the portal
            </p>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-4">
      <h4 className="text-base font-semibold text-primary">Account Type</h4>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {renderAccountTypeCard("Customer", "Customer User", "Your company's account")}
        {renderAccountTypeCard("Monto", "Monto User", "Dedicated Monto account")}
      </div>
      
      {renderMontoSetupInstructions()}
    </div>
  );
}
