import React, { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert";
import { Copy, ExternalLink, Eye, EyeOff, QrCode, User, ChevronDown, ChevronUp, Check } from "lucide-react";
import { Agent } from "@/types/smartConnection";
import { AgentStatusBadge } from "@/components/ui/agent-status-badge";
import { AgentUserTypeBadge } from "@/components/ui/agent-user-type-badge";
import { toast } from "@/hooks/use-toast";
import { Checkbox } from "@/components/ui/checkbox";
import { AccountTypeTooltip } from "./AccountTypeTooltip";

interface EditAgentModalProps {
  isOpen: boolean;
  onClose: () => void;
  onBack: () => void;
  agent: Agent;
  connectionInfo: {
    receivable: string;
    payable: string;
  };
}

type AccountType = "Customer" | "Monto";
type TwoFAMethod = "authenticator" | "email" | "phone";

export function EditAgentModal({
  isOpen,
  onClose,
  onBack,
  agent,
  connectionInfo
}: EditAgentModalProps) {
  const [showPassword, setShowPassword] = useState(false);
  const [selectedAccountType, setSelectedAccountType] = useState<AccountType>(
    agent.type === "Monto" ? "Monto" : "Customer"
  );
  const [twoFAExpanded, setTwoFAExpanded] = useState(false);
  const [selectedTwoFAMethod, setSelectedTwoFAMethod] = useState<TwoFAMethod>("authenticator");
  const [verificationCode, setVerificationCode] = useState("");
  const [emailInput, setEmailInput] = useState("");
  const [phoneInput, setPhoneInput] = useState("");
  const [montoSetupConfirmed, setMontoSetupConfirmed] = useState(false);

  // Mock credentials for demo purposes
  const credentials = {
    username: agent.portalUser,
    password: "••••••••",
    twoFA: agent.status === "Disconnected" ? "Disabled" : "Enabled",
    twoFAMethod: "Google Authenticator",
    portalLink: `https://${agent.portalName.toLowerCase().replace(/\s+/g, '')}.com`
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied to clipboard",
      description: "Text has been copied to your clipboard.",
    });
  };

  const handleSaveChanges = () => {
    console.log("Saving changes for agent:", agent.id);
    console.log("Account type:", selectedAccountType);
    console.log("2FA setup:", twoFAExpanded);
    
    toast({
      title: "Validating Connection...",
      description: "We're validating your agent configuration. This may take a moment.",
    });
    
    onClose();
  };

  const handleSetupTwoFA = () => {
    setTwoFAExpanded(!twoFAExpanded);
  };

  const handleAccountTypeSelect = (type: AccountType) => {
    setSelectedAccountType(type);
    // Reset Monto setup confirmation when switching away from Monto
    if (type !== "Monto") {
      setMontoSetupConfirmed(false);
    }
  };

  const handleMontoSetupConfirmedChange = (checked: boolean | "indeterminate") => {
    setMontoSetupConfirmed(checked === true);
  };

  const autoGeneratedEmail = `${connectionInfo.receivable.toLowerCase().replace(/\s+/g, '')}@montopay.com`;

  // Only show credentials for Customer User
  const shouldShowCredentials = selectedAccountType === "Customer";

  const isSaveDisabled = selectedAccountType === "Monto" && !montoSetupConfirmed;

  const renderAccountTypeCard = (type: AccountType, title: string, description: string) => {
    const isSelected = selectedAccountType === type;
    const isMonto = type === "Monto";
    
    return (
      <AccountTypeTooltip type={type}>
        <div
          className={`p-4 rounded-xl border cursor-pointer transition-all relative ${
            isSelected
              ? isMonto 
                ? "bg-[#EEEAFF] border-[#7B59FF]"
                : "bg-gray-100 border-gray-300"
              : "bg-white border-gray-200" + (isMonto ? " hover:border-gray-300" : "")
          }`}
          onClick={() => handleAccountTypeSelect(type)}
        >
          {isMonto && (
            <div className="absolute top-2 right-2">
              <span className="bg-green-100 text-green-800 text-xs font-medium px-2 py-1 rounded-full">
                Recommended
              </span>
            </div>
          )}
          <div className="flex items-center gap-3 mb-2">
            <User className="h-5 w-5 text-gray-600" />
            <span className="font-medium text-gray-900">{title}</span>
          </div>
          <p className="text-sm text-gray-600">{description}</p>
        </div>
      </AccountTypeTooltip>
    );
  };

  const renderMontoSetupInstructions = () => {
    if (selectedAccountType !== "Monto") return null;

    return (
      <div className="w-full p-4 bg-[#EEEAFF] border border-[#7B59FF] rounded-xl">
        <h4 className="font-medium text-gray-900 mb-4">Setup Instructions</h4>
        
        <div className="space-y-4">
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              1
            </div>
            <p className="text-sm text-gray-700">Log into your portal and navigate to user management</p>
          </div>
          
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              2
            </div>
            <div className="flex-1">
              <p className="text-sm text-gray-700 mb-2">Create a user using the auto-generated Monto email:</p>
              <div className="flex items-center gap-2">
                <div className="flex-1 p-2 bg-white border rounded text-sm text-blue-600 font-mono">
                  {autoGeneratedEmail}
                </div>
                <Button variant="outline" size="sm" onClick={() => copyToClipboard(autoGeneratedEmail)}>
                  <Copy className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
          
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              3
            </div>
            <div className="flex-1">
              <p className="text-sm text-gray-700 mb-2">Permission requirements:</p>
              <div className="space-y-1 ml-2">
                <div className="flex items-center gap-2 text-sm text-gray-700">
                  <Check className="h-4 w-4 text-green-600" />
                  <span>Full access to invoice submission</span>
                </div>
                <div className="flex items-center gap-2 text-sm text-gray-700">
                  <Check className="h-4 w-4 text-green-600" />
                  <span>Full access to portal management</span>
                </div>
              </div>
            </div>
          </div>
          
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              4
            </div>
            <p className="text-sm text-gray-700">Set a strong password and configure 2FA if required</p>
          </div>
          
          <div className="pt-4 border-t border-[#7B59FF]/20">
            <div className="flex items-center space-x-2">
              <Checkbox 
                id="monto-setup" 
                checked={montoSetupConfirmed}
                onCheckedChange={handleMontoSetupConfirmedChange}
              />
              <label htmlFor="monto-setup" className="text-sm text-gray-700 cursor-pointer">
                I've created this dedicated user in the portal
              </label>
            </div>
            <p className="text-xs text-blue-600 mt-1 ml-6">
              Check this box once you've completed the setup steps above in the portal
            </p>
          </div>
        </div>
      </div>
    );
  };

  const renderTwoFASetup = () => {
    if (!twoFAExpanded) return null;

    return (
      <div className="mt-4 p-4 border rounded-lg bg-gray-50">
        <h4 className="text-sm font-medium text-gray-900 mb-3">Choose verification method:</h4>
        
        {/* Method Selection */}
        <div className="space-y-2 mb-4">
          <label className="flex items-center space-x-3 cursor-pointer">
            <input
              type="radio"
              name="twoFAMethod"
              value="authenticator"
              checked={selectedTwoFAMethod === "authenticator"}
              onChange={(e) => setSelectedTwoFAMethod(e.target.value as TwoFAMethod)}
              className="text-blue-600"
            />
            <span className="text-sm">Authenticator App (Recommended)</span>
          </label>
          <label className="flex items-center space-x-3 cursor-pointer">
            <input
              type="radio"
              name="twoFAMethod"
              value="email"
              checked={selectedTwoFAMethod === "email"}
              onChange={(e) => setSelectedTwoFAMethod(e.target.value as TwoFAMethod)}
              className="text-blue-600"
            />
            <span className="text-sm">Email Verification</span>
          </label>
          <label className="flex items-center space-x-3 cursor-pointer">
            <input
              type="radio"
              name="twoFAMethod"
              value="phone"
              checked={selectedTwoFAMethod === "phone"}
              onChange={(e) => setSelectedTwoFAMethod(e.target.value as TwoFAMethod)}
              className="text-blue-600"
            />
            <span className="text-sm">Phone Verification</span>
          </label>
        </div>

        {/* Method-specific setup */}
        {selectedTwoFAMethod === "authenticator" && (
          <div className="space-y-3">
            <p className="text-sm text-gray-600">
              Download an authenticator app (Google Authenticator, Authy) and scan the QR code below:
            </p>
            <div className="flex justify-center p-4 bg-white border rounded">
              <div className="w-32 h-32 bg-gray-200 flex items-center justify-center">
                <QrCode className="h-16 w-16 text-gray-400" />
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Enter 6-digit code from authenticator app:
              </label>
              <input
                type="text"
                value={verificationCode}
                onChange={(e) => setVerificationCode(e.target.value)}
                className="w-full p-2 border rounded text-sm"
                placeholder="123456"
                maxLength={6}
              />
            </div>
          </div>
        )}

        {selectedTwoFAMethod === "email" && (
          <div className="space-y-3">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Email address:
              </label>
              <input
                type="email"
                value={emailInput}
                onChange={(e) => setEmailInput(e.target.value)}
                className="w-full p-2 border rounded text-sm"
                placeholder="Enter email address"
              />
            </div>
            <Button variant="outline" size="sm" disabled={!emailInput}>
              Send Test Code
            </Button>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Enter verification code:
              </label>
              <input
                type="text"
                value={verificationCode}
                onChange={(e) => setVerificationCode(e.target.value)}
                className="w-full p-2 border rounded text-sm"
                placeholder="123456"
                maxLength={6}
                disabled={!emailInput}
              />
            </div>
          </div>
        )}

        {selectedTwoFAMethod === "phone" && (
          <div className="space-y-3">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Phone number:
              </label>
              <input
                type="text"
                value={phoneInput}
                onChange={(e) => setPhoneInput(e.target.value)}
                className="w-full p-2 border rounded text-sm"
                placeholder="+1 555-123-4567"
              />
            </div>
            <Button variant="outline" size="sm" disabled={!phoneInput}>
              Send Test SMS
            </Button>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Enter SMS code:
              </label>
              <input
                type="text"
                value={verificationCode}
                onChange={(e) => setVerificationCode(e.target.value)}
                className="w-full p-2 border rounded text-sm"
                placeholder="123456"
                maxLength={6}
                disabled={!phoneInput}
              />
            </div>
          </div>
        )}
      </div>
    );
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <div className="flex items-center gap-3">
            <DialogTitle className="text-lg font-semibold text-gray-900">
              Edit Agent
            </DialogTitle>
            <AgentStatusBadge status={agent.status} />
            <AgentUserTypeBadge type={agent.type} />
          </div>
          
          <div className="text-sm text-gray-600 mt-6 text-left">
            {connectionInfo.receivable} → {connectionInfo.payable}
          </div>
          
          <Separator className="mt-6" />
        </DialogHeader>
        
        <div className="space-y-4 mt-6">
          {/* Attention Banner for Disconnected Agents - only show for Customer User */}
          {agent.status === "Disconnected" && selectedAccountType === "Customer" && (
            <div className="bg-orange-100 border border-orange-300 text-orange-800 px-4 py-2 rounded-md flex items-start gap-2 text-sm">
              <span className="text-orange-500 mt-0.5">⚠️</span>
              <div>
                <span className="font-bold">Two-Factor Authentication Required</span>
                <br />
                <span>The portal requires 2FA to be configured for this account.</span>
              </div>
            </div>
          )}

          {/* Account Type Section */}
          <div className="space-y-4">
            <h4 className="text-base font-semibold text-primary">Account Type</h4>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {renderAccountTypeCard("Customer", "Customer User", "Your company's account")}
              {renderAccountTypeCard("Monto", "Monto User", "Dedicated Monto account")}
            </div>
            
            {/* Setup instructions - full width below both cards */}
            {renderMontoSetupInstructions()}
          </div>

          {/* Conditional Credentials Section */}
          {shouldShowCredentials && (
            <div className="space-y-4">
              <h4 className="text-base font-semibold text-primary">Credentials</h4>
              
              <div className="space-y-4 max-w-md">
                <div>
                  <label className="block text-sm font-medium text-muted-foreground mb-1">
                    Portal Link
                  </label>
                  <div className="flex items-center gap-2">
                    <input
                      type="text"
                      defaultValue={credentials.portalLink}
                      className="flex-1 p-2 bg-white border rounded text-sm text-blue-600"
                    />
                    <Button variant="outline" size="sm" onClick={() => window.open(credentials.portalLink, '_blank')}>
                      <ExternalLink className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-muted-foreground mb-1">
                    Username
                  </label>
                  <div className="flex items-center gap-2">
                    <input
                      type="text"
                      defaultValue={credentials.username}
                      className="flex-1 p-2 bg-white border rounded text-sm"
                    />
                    <Button variant="outline" size="sm" onClick={() => copyToClipboard(credentials.username)}>
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-muted-foreground mb-1">
                    Password
                  </label>
                  <div className="flex items-center gap-2">
                    <input
                      type={showPassword ? "text" : "password"}
                      defaultValue="demo_password_123"
                      className="flex-1 p-2 bg-white border rounded text-sm font-mono"
                    />
                    <Button variant="outline" size="sm" onClick={() => setShowPassword(!showPassword)}>
                      {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => copyToClipboard("demo_password_123")}>
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* Conditional Two-Factor Authentication Section */}
          {shouldShowCredentials && (
            <div className="space-y-4">
              <h4 className="text-base font-semibold text-primary">🔐 Two-Factor Authentication</h4>
              <div className="space-y-2 max-w-md">
                <div className="flex items-center justify-between p-2 bg-gray-50 border rounded text-sm">
                  <div>
                    <span className="text-gray-500">Status: </span>
                    <span className="text-gray-500">{credentials.twoFA}</span>
                    <div className="text-xs text-gray-500 mt-1">Required by portal</div>
                  </div>
                  {credentials.twoFA === "Disabled" && (
                    <Button 
                      onClick={handleSetupTwoFA}
                      className="bg-green-600 hover:bg-green-700 text-white text-xs px-3 py-1"
                      size="sm"
                    >
                      {twoFAExpanded ? (
                        <>
                          <ChevronUp className="h-3 w-3 mr-1" />
                          Hide Setup
                        </>
                      ) : (
                        "Setup Required"
                      )}
                    </Button>
                  )}
                  {credentials.twoFA === "Enabled" && (
                    <div className="flex items-center gap-2">
                      <span className="text-gray-600 text-xs">via {credentials.twoFAMethod}</span>
                      <Button variant="outline" size="sm" className="text-red-600 text-xs">
                        Disable
                      </Button>
                    </div>
                  )}
                </div>
                
                {renderTwoFASetup()}
                
                {credentials.twoFA === "Enabled" && (
                  <div className="flex items-center gap-2 text-xs text-gray-500">
                    <QrCode className="h-3 w-3" />
                    <span>Set up during agent configuration with {credentials.twoFAMethod}</span>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
          
        {/* Action Footer */}
        <div className="flex justify-between items-center pt-4 border-t mt-4">
          <div className="flex gap-2">
            <Button variant="outline" onClick={onBack}>
              Back
            </Button>
            <Button variant="outline" onClick={onClose}>
              Cancel
            </Button>
          </div>
          <Button 
            onClick={handleSaveChanges} 
            disabled={isSaveDisabled}
            style={{ backgroundColor: isSaveDisabled ? '#9CA3AF' : '#7B59FF' }}
            className={`hover:opacity-90 ${isSaveDisabled ? 'cursor-not-allowed' : ''}`}
          >
            Save Changes
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
