
import React from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert";
import { Copy, ExternalLink, Eye, EyeOff, QrCode, User, Check } from "lucide-react";
import { useState } from "react";
import { Agent } from "@/types/smartConnection";
import { AgentStatusBadge } from "@/components/ui/agent-status-badge";
import { AgentUserTypeBadge } from "@/components/ui/agent-user-type-badge";
import { EditAgentModal } from "./EditAgentModal";
import { Checkbox } from "@/components/ui/checkbox";

interface ViewDetailsModalProps {
  isOpen: boolean;
  onClose: () => void;
  agent: Agent;
  connectionInfo: {
    receivable: string;
    payable: string;
  };
}

type AccountType = "Customer" | "Monto";

export function ViewDetailsModal({
  isOpen,
  onClose,
  agent,
  connectionInfo
}: ViewDetailsModalProps) {
  const [showPassword, setShowPassword] = useState(false);
  const [isEditMode, setIsEditMode] = useState(false);
  const [selectedAccountType, setSelectedAccountType] = useState<AccountType>("Customer");
  const [montoSetupConfirmed, setMontoSetupConfirmed] = useState(false);

  // Mock credentials for demo purposes
  const credentials = {
    username: agent.portalUser,
    password: "••••••••",
    twoFA: agent.status === "Disconnected" ? "Disabled" : "Enabled",
    twoFAMethod: "Google Authenticator",
    portalLink: `https://${agent.portalName.toLowerCase().replace(/\s+/g, '')}.com`
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  const handleEdit = () => {
    setIsEditMode(true);
  };

  const handleConfigureSettings = () => {
    setIsEditMode(true);
  };

  const handleBackToView = () => {
    setIsEditMode(false);
  };

  const handleCloseEdit = () => {
    setIsEditMode(false);
    onClose();
  };

  const handleAccountTypeSelect = (type: AccountType) => {
    setSelectedAccountType(type);
  };

  const handleMontoSetupConfirmedChange = (checked: boolean | "indeterminate") => {
    setMontoSetupConfirmed(checked === true);
  };

  const autoGeneratedEmail = `${connectionInfo.receivable.toLowerCase().replace(/\s+/g, '')}@montopay.com`;

  // Updated conditional display logic - only show credentials for Customer User
  const shouldShowCredentials = selectedAccountType === "Customer";

  const shouldShowTwoFABanner = agent.status === "Disconnected" && selectedAccountType === "Customer";

  const renderAccountTypeCard = (type: AccountType, title: string, description: string) => {
    const isSelected = selectedAccountType === type;
    const isMonto = type === "Monto";
    
    return (
      <div
        className={`p-4 rounded-xl border cursor-pointer transition-all relative ${
          isSelected
            ? isMonto 
              ? "bg-[#EEEAFF] border-[#7B59FF]"
              : "bg-gray-100 border-gray-300"
            : "bg-white border-gray-200 hover:border-gray-300"
        }`}
        onClick={() => handleAccountTypeSelect(type)}
      >
        {isMonto && (
          <div className="absolute top-2 right-2">
            <span className="bg-green-100 text-green-800 text-xs font-medium px-2 py-1 rounded-full">
              Recommended
            </span>
          </div>
        )}
        <div className="flex items-center gap-3 mb-2">
          <User className="h-5 w-5 text-gray-600" />
          <span className="font-medium text-gray-900">{title}</span>
        </div>
        <p className="text-sm text-gray-600">{description}</p>
      </div>
    );
  };

  const renderMontoSetupInstructions = () => {
    if (selectedAccountType !== "Monto") return null;

    return (
      <div className="p-4 bg-[#EEEAFF] border border-[#7B59FF] rounded-xl">
        <h4 className="font-medium text-gray-900 mb-4">Setup Instructions</h4>
        
        <div className="space-y-4">
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              1
            </div>
            <p className="text-sm text-gray-700">Log into your portal and navigate to user management</p>
          </div>
          
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              2
            </div>
            <div className="flex-1">
              <p className="text-sm text-gray-700 mb-2">Create a user using the auto-generated Monto email:</p>
              <div className="flex items-center gap-2">
                <div className="flex-1 p-2 bg-white border rounded text-sm text-blue-600 font-mono">
                  {autoGeneratedEmail}
                </div>
                <Button variant="outline" size="sm" onClick={() => copyToClipboard(autoGeneratedEmail)}>
                  <Copy className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
          
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              3
            </div>
            <div className="flex-1">
              <p className="text-sm text-gray-700 mb-2">Permission requirements:</p>
              <div className="space-y-1 ml-2">
                <div className="flex items-center gap-2 text-sm text-gray-700">
                  <Check className="h-4 w-4 text-green-600" />
                  <span>Full access to invoice submission</span>
                </div>
                <div className="flex items-center gap-2 text-sm text-gray-700">
                  <Check className="h-4 w-4 text-green-600" />
                  <span>Full access to portal management</span>
                </div>
              </div>
            </div>
          </div>
          
          <div className="flex items-start gap-3">
            <div className="bg-[#7B59FF] text-white rounded-full w-6 h-6 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
              4
            </div>
            <p className="text-sm text-gray-700">Set a strong password and configure 2FA if required</p>
          </div>
          
          <div className="pt-4 border-t border-[#7B59FF]/20">
            <div className="flex items-center space-x-2">
              <Checkbox 
                id="monto-setup" 
                checked={montoSetupConfirmed}
                onCheckedChange={handleMontoSetupConfirmedChange}
              />
              <label htmlFor="monto-setup" className="text-sm text-gray-700 cursor-pointer">
                I've created this dedicated user in the portal
              </label>
            </div>
            <p className="text-xs text-blue-600 mt-1 ml-6">
              Check this box once you've completed the setup steps above in the portal
            </p>
          </div>
        </div>
      </div>
    );
  };

  if (isEditMode) {
    return (
      <EditAgentModal
        isOpen={isOpen}
        onClose={handleCloseEdit}
        onBack={handleBackToView}
        agent={agent}
        connectionInfo={connectionInfo}
      />
    );
  }

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          {/* Title and status badges in the same row */}
          <div className="flex items-center gap-3">
            <DialogTitle className="text-lg font-semibold text-gray-900">
              Agent Details
            </DialogTitle>
            <AgentStatusBadge status={agent.status} />
            <AgentUserTypeBadge type={agent.type} />
          </div>
          
          {/* Subtitle with improved spacing */}
          <div className="text-sm text-gray-600 mt-6 text-left my-[21px]">
            {connectionInfo.receivable} → {connectionInfo.payable}
          </div>
          
          {/* Separator with balanced spacing */}
          <Separator className="mt-8 my-[25px]" />
        </DialogHeader>
        
        <div className="space-y-6 mt-8">
          {/* Attention Banner for Disconnected Agents - reduced padding */}
          {shouldShowTwoFABanner && (
            <div className="flex items-start gap-2 bg-orange-50 border border-orange-200 rounded-md p-3 text-sm">
              <span className="text-orange-500 mt-0.5">⚠️</span>
              <div className="text-orange-800">
                <span className="font-bold">Two-Factor Authentication Required</span>
                <br />
                The portal requires 2FA to be configured for this account.{" "}
                <button 
                  onClick={handleConfigureSettings}
                  className="underline font-medium hover:text-orange-900"
                >
                  Configure settings
                </button>
              </div>
            </div>
          )}

          {/* Account Type Section */}
          <div className="space-y-4">
            <h3 className="text-sm font-medium text-gray-900">Account Type</h3>
            
            {/* Account type cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {renderAccountTypeCard("Customer", "Customer User", "Your company's account")}
              {renderAccountTypeCard("Monto", "Monto User", "Dedicated Monto account")}
            </div>
            
            {/* Monto setup instructions - full width below both cards */}
            {renderMontoSetupInstructions()}
          </div>

          {/* Conditional Credentials Section - only for Customer User */}
          {shouldShowCredentials && (
            <div className="space-y-4">
              <h3 className="text-sm font-medium text-gray-900">Credentials</h3>
              
              <div className="w-full max-w-md space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Portal Link
                  </label>
                  <div className="flex items-center gap-2">
                    <div className="flex-1 p-2 bg-gray-50 border rounded text-sm text-blue-600">
                      {credentials.portalLink}
                    </div>
                    <Button variant="outline" size="sm" onClick={() => window.open(credentials.portalLink, '_blank')}>
                      <ExternalLink className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Username
                  </label>
                  <div className="flex items-center gap-2">
                    <div className="flex-1 p-2 bg-gray-50 border rounded text-sm">
                      {credentials.username}
                    </div>
                    <Button variant="outline" size="sm" onClick={() => copyToClipboard(credentials.username)}>
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Password
                  </label>
                  <div className="flex items-center gap-2">
                    <div className="flex-1 p-2 bg-gray-50 border rounded text-sm font-mono">
                      {showPassword ? "demo_password_123" : credentials.password}
                    </div>
                    <Button variant="outline" size="sm" onClick={() => setShowPassword(!showPassword)}>
                      {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => copyToClipboard("demo_password_123")}>
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* Conditional Two-Factor Authentication Section - only for Customer User */}
          {shouldShowCredentials && (
            <div className="space-y-4">
              <h3 className="text-sm font-medium text-gray-900">🔐 Two-Factor Authentication</h3>
              <div className="w-full max-w-md space-y-2">
                <div className="flex items-center justify-between p-2 bg-gray-50 border rounded text-sm">
                  <div>
                    <span className="text-gray-500">Status: </span>
                    <span className="text-gray-500">{credentials.twoFA}</span>
                    <div className="text-xs text-gray-500 mt-1">Required by portal</div>
                  </div>
                  {credentials.twoFA === "Disabled" && (
                    <Button 
                      onClick={handleConfigureSettings}
                      className="bg-green-600 hover:bg-green-700 text-white text-xs px-3 py-1"
                      size="sm"
                    >
                      Setup Required
                    </Button>
                  )}
                  {credentials.twoFA === "Enabled" && (
                    <div className="flex items-center gap-2">
                      <span className="text-gray-600 text-xs">via {credentials.twoFAMethod}</span>
                    </div>
                  )}
                </div>
                
                {credentials.twoFA === "Enabled" && (
                  <div className="flex items-center gap-2 text-xs text-gray-500">
                    <QrCode className="h-3 w-3" />
                    <span>Set up during agent configuration with {credentials.twoFAMethod}</span>
                  </div>
                )}
              </div>
            </div>
          )}
          
          {/* Updated Footer with purple Edit Agent button */}
          <div className="flex justify-between items-center pt-4 border-t">
            <Button variant="outline" onClick={onClose}>
              Close
            </Button>
            <Button 
              onClick={handleEdit} 
              style={{ backgroundColor: '#7B59FF' }}
              className="hover:opacity-90"
            >
              Edit Agent
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
